# Generated by Django 6.0.6 on 2026-06-22 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_turno', models.CharField(editable=False, max_length=10, unique=True)),
                ('tramite', models.CharField(choices=[('dni-5-8', 'DNI – Actualización 5-8 años'), ('dni-14', 'DNI – Actualización 14 años'), ('dni-domicilio', 'DNI – Cambio de domicilio'), ('dni-nuevo', 'DNI – Nuevo ejemplar'), ('pasaporte', 'Pasaporte')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asistio', 'Asistió'), ('no_asistio', 'No asistió'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('origen', models.CharField(choices=[('sistema', 'Sistema — solicitado por el ciudadano'), ('manual', 'Manual — cargado por empleado')], default='sistema', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_atendidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
