# Generated by Django 6.0.4 on 2026-06-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='es_gratuito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tramite',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
